/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopfinal.gui;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import shopfinal.ButtonActionHolder;
import shopfinal.managers.ActionManager;
import shopfinal.models.Department;

public class AddDepartment extends javax.swing.JPanel {
    
    public ButtonActionHolder actionHolder = null;

    /**
     * Creates new form FindById
     */
    public AddDepartment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        pibLabel = new javax.swing.JLabel();
        pib = new javax.swing.JTextField();
        performButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(435, 600));
        setMinimumSize(new java.awt.Dimension(435, 600));
        setPreferredSize(new java.awt.Dimension(435, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Додати відділ");
        title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 180, 30));

        pibLabel.setText("Назва:");
        add(pibLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 60, 30));

        pib.setMinimumSize(new java.awt.Dimension(80, 20));
        pib.setPreferredSize(new java.awt.Dimension(80, 20));
        add(pib, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 270, 30));

        performButton.setText("Виконати");
        performButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performButtonActionPerformed(evt);
            }
        });
        add(performButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 140, -1));

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void performButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performButtonActionPerformed
        if (actionHolder != null) {
            actionHolder.performAction();
        }
    }//GEN-LAST:event_performButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton performButton;
    private javax.swing.JTextField pib;
    private javax.swing.JLabel pibLabel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
