/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopfinal.gui;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import shopfinal.ButtonActionHolder;
import shopfinal.managers.ActionManager;
import shopfinal.models.Department;

public class AddEmployee extends javax.swing.JPanel {

    public HashMap<String, Integer> depMap = new HashMap<String, Integer>();
    public ButtonActionHolder actionHolder = null;

    /**
     * Creates new form FindById
     */
    public AddEmployee() {
        initComponents();
        initDepartments();
    }

    private void initDepartments() {
        ActionManager.Result result;
        try {
            result = ActionManager.getInstance().performAction(ActionManager.Action.GET_ALL_DEPARTMENTS, null);
            departments.removeAllItems();
            ArrayList<Department> deps = (ArrayList<Department>) result.data;
            for (int i = 0; i < deps.size(); ++i) {
                Department dep = deps.get(i);
                departments.addItem(dep.name);
                depMap.put(dep.name, dep.id);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        departmentLabel = new javax.swing.JLabel();
        performButton = new javax.swing.JButton();
        pibLabel = new javax.swing.JLabel();
        pib = new javax.swing.JTextField();
        currencyLabel = new javax.swing.JLabel();
        cost = new javax.swing.JTextField();
        departments = new javax.swing.JComboBox<>();
        costLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(435, 600));
        setMinimumSize(new java.awt.Dimension(435, 600));
        setPreferredSize(new java.awt.Dimension(435, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Додати працівника");
        title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 160, 30));

        departmentLabel.setText("Відділ:");
        add(departmentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 60, 30));
        departmentLabel.getAccessibleContext().setAccessibleName("id");

        performButton.setText("Виконати");
        performButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performButtonActionPerformed(evt);
            }
        });
        add(performButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 140, -1));

        pibLabel.setText("ПІБ:");
        add(pibLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 60, 30));

        pib.setMinimumSize(new java.awt.Dimension(80, 20));
        pib.setPreferredSize(new java.awt.Dimension(80, 20));
        pib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pibActionPerformed(evt);
            }
        });
        add(pib, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 270, 30));

        currencyLabel.setText("(грн)");
        add(currencyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 60, 30));

        cost.setMinimumSize(new java.awt.Dimension(80, 20));
        cost.setPreferredSize(new java.awt.Dimension(80, 20));
        cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costActionPerformed(evt);
            }
        });
        add(cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 150, 30));

        departments.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(departments, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 140, 260, -1));

        costLabel1.setText("Оклад:");
        add(costLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 60, 30));

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void performButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performButtonActionPerformed
        if (actionHolder != null) {
            actionHolder.performAction();
        }
        try {
            ActionManager.ActionParams params = new ActionManager.ActionParams();
            params.dataArr = new Object[3];
            params.dataArr[0] = pib.getText();
            params.dataArr[1] = Integer.parseInt(cost.getText());
            String depName = String.valueOf(departments.getSelectedItem());
            params.dataArr[2] = depMap.get(depName);
            ActionManager.getInstance().performAction(ActionManager.Action.ADD_EMPLOYEE, params);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_performButtonActionPerformed

    private void pibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pibActionPerformed

    private void costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costActionPerformed

    public String getLabelName() {
        if (cost.getText() != null && cost.getText() != "") {
            return cost.getText();
        }

        return "";
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cost;
    private javax.swing.JLabel costLabel1;
    private javax.swing.JLabel currencyLabel;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JComboBox<String> departments;
    private javax.swing.JButton performButton;
    private javax.swing.JTextField pib;
    private javax.swing.JLabel pibLabel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
