/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopfinal.gui;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import shopfinal.ButtonActionHolder;
import shopfinal.managers.ActionManager;
import shopfinal.managers.ActionManager.Result;
import shopfinal.models.Department;
import shopfinal.models.Provider;

public class AddGoods extends javax.swing.JPanel {

    public ButtonActionHolder actionHolder = null;
    private HashMap<String, Integer> depMap = new HashMap<String, Integer>();

    public AddGoods() {
        initComponents();
        initAvailableProviders();
        initAvailableDepartments();
    }

    private void initAvailableProviders() {
        try {
            availableProviders.removeAllItems();
            Result result = ActionManager.getInstance().performAction(ActionManager.Action.GET_ALL_PROVIDERS, null);
            ArrayList<Provider> providers = (ArrayList<Provider>) result.data;
            for (int i = 0; i < providers.size(); ++i) {
                availableProviders.addItem(providers.get(i).name);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddGoods.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initAvailableDepartments() {
        try {
            availableDepartments.removeAllItems();
            Result result = ActionManager.getInstance().performAction(ActionManager.Action.GET_ALL_DEPARTMENTS, null);
            ArrayList<Department> departments = (ArrayList<Department>) result.data;
            for (int i = 0; i < departments.size(); ++i) {
                Department department = departments.get(i);
                availableDepartments.addItem(department.name);
                depMap.put(department.name, department.id);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddGoods.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        departmentLabel = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        performButton = new javax.swing.JButton();
        nameLabel1 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        nameLabel2 = new javax.swing.JLabel();
        availableDepartments = new javax.swing.JComboBox<>();
        numberLabel1 = new javax.swing.JLabel();
        availableProviders = new javax.swing.JComboBox<>();
        departmentLabel1 = new javax.swing.JLabel();
        number1 = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        costLabel = new javax.swing.JLabel();
        cost = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        departmentLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(435, 600));
        setMinimumSize(new java.awt.Dimension(435, 600));
        setPreferredSize(new java.awt.Dimension(435, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Додати товар");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 160, 30));

        departmentLabel.setText("(од)");
        add(departmentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 80, 30));
        departmentLabel.getAccessibleContext().setAccessibleName("id");

        date.setMinimumSize(new java.awt.Dimension(80, 20));
        date.setPreferredSize(new java.awt.Dimension(80, 20));
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 130, 30));

        performButton.setText("Виконати");
        performButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performButtonActionPerformed(evt);
            }
        });
        add(performButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 140, -1));

        nameLabel1.setText("Постачальник:");
        add(nameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 100, 30));

        name1.setMinimumSize(new java.awt.Dimension(80, 20));
        name1.setPreferredSize(new java.awt.Dimension(80, 20));
        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 230, 30));

        nameLabel2.setText("Назва:");
        add(nameLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 80, 30));

        availableDepartments.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(availableDepartments, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 230, 20));

        numberLabel1.setText("Кількість:");
        add(numberLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, 30));

        availableProviders.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(availableProviders, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 230, 20));

        departmentLabel1.setText("Відділ:");
        add(departmentLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 80, 30));

        number1.setMinimumSize(new java.awt.Dimension(80, 20));
        number1.setPreferredSize(new java.awt.Dimension(80, 20));
        number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number1ActionPerformed(evt);
            }
        });
        add(number1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 130, 30));

        dateLabel.setText("Дата:");
        add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 80, 30));

        costLabel.setText("Собіварітість:");
        add(costLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 90, 30));

        cost.setMinimumSize(new java.awt.Dimension(80, 20));
        cost.setPreferredSize(new java.awt.Dimension(80, 20));
        cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costActionPerformed(evt);
            }
        });
        add(cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 130, 30));

        priceLabel.setText("Ціна:");
        add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 80, 30));

        price.setMinimumSize(new java.awt.Dimension(80, 20));
        price.setPreferredSize(new java.awt.Dimension(80, 20));
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 130, 30));

        departmentLabel2.setText("(грн)");
        add(departmentLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 80, 30));

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void performButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performButtonActionPerformed
        if (actionHolder != null) {
            actionHolder.performAction();
        }
    }//GEN-LAST:event_performButtonActionPerformed

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_number1ActionPerformed

    private void costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    public String getLabelName() {
        if (date.getText() != null && date.getText() != "") {
            return date.getText();
        }

        return "";
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> availableDepartments;
    private javax.swing.JComboBox<String> availableProviders;
    private javax.swing.JTextField cost;
    private javax.swing.JLabel costLabel;
    private javax.swing.JTextField date;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JLabel departmentLabel1;
    private javax.swing.JLabel departmentLabel2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField name1;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JTextField number1;
    private javax.swing.JLabel numberLabel1;
    private javax.swing.JButton performButton;
    private javax.swing.JTextField price;
    private javax.swing.JLabel priceLabel;
    // End of variables declaration//GEN-END:variables
}
