/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopfinal.gui;

import java.awt.Component;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import shopfinal.managers.ActionManager;
import shopfinal.managers.ActionManager.ActionParams;
import shopfinal.managers.ActionManager.Result;
import shopfinal.models.Goods;
import shopfinal.models.Provider;

public class AddOrdering extends javax.swing.JPanel {

    private final HashMap<String, Goods> goodsMap = new HashMap<String, Goods>();
    private String selectedProvider;
    /**
     * Creates new form FindById
     */
    public AddOrdering() {
        initComponents();
        addAvailableProviders();
        addAvailableGoods();
    }

    private void addAvailableGoods() {
        try {
            ActionParams params = new ActionParams();
            params.strValue1 = String.valueOf(availableProviders.getSelectedItem());
            Result result = ActionManager.getInstance().performAction(ActionManager.Action.GET_SELECTED_PROVIDER_GOODS, params);
            availableGoods.removeAllItems();
            ArrayList<Goods> goods = (ArrayList<Goods>) result.data;
            for (int i = 0; i < goods.size(); ++i) {
                String goodsName = goods.get(i).name;
                if (!goodsMap.containsKey(goodsName)) {
                    goodsMap.put(goodsName, goods.get(i));
                }
                availableGoods.addItem(goodsName);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddOrdering.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    private void addAvailableProviders() {
        try {
            Result result = ActionManager.getInstance().performAction(ActionManager.Action.GET_ALL_PROVIDERS, null);
            availableProviders.removeAllItems();
            ArrayList<Provider> providers = (ArrayList<Provider>) result.data;
            for (int i = 0; i < providers.size(); ++i) {
                availableProviders.addItem(providers.get(i).name);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddOrdering.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLayeredPane1 = new javax.swing.JLayeredPane();
        goodsLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        scroll = new javax.swing.JScrollPane();
        content = new javax.swing.JPanel();
        priceLabel = new javax.swing.JLabel();
        availableGoods = new javax.swing.JComboBox<>();
        okButton = new javax.swing.JButton();
        performButton = new javax.swing.JButton();
        numberLabel = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        availableProviders = new javax.swing.JComboBox<>();
        providerLabel1 = new javax.swing.JLabel();
        showSelectedProviderGoods = new javax.swing.JButton();
        dateLabel1 = new javax.swing.JLabel();
        date1 = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(435, 600));
        setMinimumSize(new java.awt.Dimension(435, 600));
        setPreferredSize(new java.awt.Dimension(435, 600));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        goodsLabel.setText("Товар:");
        jLayeredPane1.add(goodsLabel);
        goodsLabel.setBounds(20, 110, 90, 20);
        goodsLabel.getAccessibleContext().setAccessibleName("id");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Додати замовлення");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(140, 10, 140, 20);

        price.setMinimumSize(new java.awt.Dimension(80, 20));
        price.setPreferredSize(new java.awt.Dimension(80, 20));
        jLayeredPane1.add(price);
        price.setBounds(120, 200, 100, 30);

        scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        content.setLayout(new javax.swing.BoxLayout(content, javax.swing.BoxLayout.Y_AXIS));
        scroll.setViewportView(content);

        jLayeredPane1.add(scroll);
        scroll.setBounds(10, 240, 420, 240);

        priceLabel.setText("Ціна:");
        jLayeredPane1.add(priceLabel);
        priceLabel.setBounds(20, 200, 70, 30);

        availableGoods.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        availableGoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableGoodsActionPerformed(evt);
            }
        });
        jLayeredPane1.add(availableGoods);
        availableGoods.setBounds(120, 110, 280, 20);

        okButton.setText("+");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(okButton);
        okButton.setBounds(380, 150, 40, 30);

        performButton.setText("Виконати");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${alignmentY}"), performButton, org.jdesktop.beansbinding.BeanProperty.create("alignmentY"));
        bindingGroup.addBinding(binding);

        performButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performButtonActionPerformed(evt);
            }
        });
        jLayeredPane1.add(performButton);
        performButton.setBounds(130, 490, 180, 30);

        numberLabel.setText("Кількість:");
        jLayeredPane1.add(numberLabel);
        numberLabel.setBounds(20, 140, 70, 30);

        number.setMinimumSize(new java.awt.Dimension(80, 20));
        number.setPreferredSize(new java.awt.Dimension(80, 20));
        jLayeredPane1.add(number);
        number.setBounds(120, 140, 100, 30);

        availableProviders.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jLayeredPane1.add(availableProviders);
        availableProviders.setBounds(120, 40, 280, 20);

        providerLabel1.setText("Постачальник:");
        jLayeredPane1.add(providerLabel1);
        providerLabel1.setBounds(20, 40, 90, 20);

        showSelectedProviderGoods.setText("Переглянути товари обраного постачальника");
        showSelectedProviderGoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSelectedProviderGoodsActionPerformed(evt);
            }
        });
        jLayeredPane1.add(showSelectedProviderGoods);
        showSelectedProviderGoods.setBounds(70, 70, 300, 23);

        dateLabel1.setText("Дата:");
        jLayeredPane1.add(dateLabel1);
        dateLabel1.setBounds(20, 170, 70, 30);

        date1.setMinimumSize(new java.awt.Dimension(80, 20));
        date1.setPreferredSize(new java.awt.Dimension(80, 20));
        jLayeredPane1.add(date1);
        date1.setBounds(120, 170, 100, 30);

        add(jLayeredPane1);

        getAccessibleContext().setAccessibleParent(this);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void performButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performButtonActionPerformed
        ArrayList<Goods> goods = new ArrayList<Goods>();
        System.out.println("perform button");
        Component[] children = content.getComponents();
        for (int i = 0; i < children.length; ++i) {
            if (children[i].isVisible()) {
                GoodsPreviewItem item = (GoodsPreviewItem) children[i];
                if (item != null) {
                    Goods goodsItem = goodsMap.get(item.getName());
                    if (goodsItem.number > item.getNumber()) {
                        goodsItem.number -= item.getNumber();
                        goods.add(goodsItem);
                    }
                }
            }
        }
    }//GEN-LAST:event_performButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        String goodsName = String.valueOf(availableGoods.getSelectedItem());
        Goods goodsItem = goodsMap.get(goodsName);
        if (price.getText() != null && !"".equals(price.getText())) {
            GoodsPreviewItem item = new GoodsPreviewItem();
            item.setLabelName(goodsItem.name);
            item.setLabelNumber(price.getText());
            content.add(item);
            content.repaint();
            content.revalidate();
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void availableGoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableGoodsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availableGoodsActionPerformed

    private void showSelectedProviderGoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSelectedProviderGoodsActionPerformed
        addAvailableGoods();
    }//GEN-LAST:event_showSelectedProviderGoodsActionPerformed

    public int getPrice() {
        return Integer.parseInt(price.getText());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> availableGoods;
    private javax.swing.JComboBox<String> availableProviders;
    private javax.swing.JPanel content;
    private javax.swing.JTextField date1;
    private javax.swing.JLabel dateLabel1;
    private javax.swing.JLabel goodsLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField number;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JButton performButton;
    private javax.swing.JTextField price;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel providerLabel1;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JButton showSelectedProviderGoods;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
