/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopfinal.gui;

import java.awt.Component;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import shopfinal.ButtonActionHolder;
import shopfinal.managers.ActionManager;
import shopfinal.managers.ActionManager.ActionParams;
import shopfinal.managers.ActionManager.Result;
import shopfinal.models.Department;
import shopfinal.models.Employee;
import shopfinal.models.Goods;
import shopfinal.models.Provider;

public class AddOrdering2 extends javax.swing.JPanel {

    public ButtonActionHolder actionHolder = null;
    private final HashMap<String, Goods> goodsMap = new HashMap<String, Goods>();
    private final HashMap<String, Employee> employeeMap = new HashMap<String, Employee>();
    private final HashMap<String, Provider> providersMap = new HashMap<String, Provider>();

    public AddOrdering2() {
        initComponents();
        addAvailableProviders();
        addAvailableGoods();
        addAvailableEmployees();
    }
    
    private void addAvailableEmployees() {
        try {
            Result result = ActionManager.getInstance().performAction(ActionManager.Action.GET_ALL_EMPLOYEES, null);
            availableEmployees.removeAllItems();
            ArrayList<Employee> employees = (ArrayList<Employee>) result.data;
            for (int i = 0; i < employees.size(); ++i) {
                Employee e = employees.get(i);
                if (!employeeMap.containsKey(e.pib)) {
                    employeeMap.put(e.pib, e);
                }
                availableEmployees.addItem(e.pib);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddOrdering2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void addAvailableGoods() {
        try {
            ActionParams params = new ActionParams();
            params.strValue1 = String.valueOf(availableProviders.getSelectedItem());
            Result result = ActionManager.getInstance().performAction(ActionManager.Action.GET_SELECTED_PROVIDER_GOODS, params);
            availableGoods.removeAllItems();
            ArrayList<Goods> goods = (ArrayList<Goods>) result.data;
            for (int i = 0; i < goods.size(); ++i) {
                String goodsName = goods.get(i).name;
                if (!goodsMap.containsKey(goodsName)) {
                    goodsMap.put(goodsName, goods.get(i));
                }
                availableGoods.addItem(goodsName);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddOrdering2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    private void addAvailableProviders() {
        try {
            Result result = ActionManager.getInstance().performAction(ActionManager.Action.GET_ALL_PROVIDERS, null);
            availableProviders.removeAllItems();
            ArrayList<Provider> providers = (ArrayList<Provider>) result.data;
            for (int i = 0; i < providers.size(); ++i) {
                Provider provider = providers.get(i);
                availableProviders.addItem(provider.name);
                providersMap.put(provider.name, provider);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddOrdering2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        departmentLabel = new javax.swing.JLabel();
        performButton = new javax.swing.JButton();
        nameLabel1 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        nameLabel2 = new javax.swing.JLabel();
        availableGoods = new javax.swing.JComboBox<>();
        numberLabel1 = new javax.swing.JLabel();
        availableEmployees = new javax.swing.JComboBox<>();
        departmentLabel1 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        departmentLabel2 = new javax.swing.JLabel();
        availableProviders = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        content = new javax.swing.JPanel();
        showSelectedProviderGoods = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(435, 600));
        setMinimumSize(new java.awt.Dimension(435, 600));
        setPreferredSize(new java.awt.Dimension(435, 600));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Додати замовлення");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        departmentLabel.setText("(од)");

        performButton.setText("Виконати");
        performButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performButtonActionPerformed(evt);
            }
        });

        nameLabel1.setText("Працівник:");

        date.setMinimumSize(new java.awt.Dimension(80, 20));
        date.setPreferredSize(new java.awt.Dimension(80, 20));

        nameLabel2.setText("Дата:");

        availableGoods.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        numberLabel1.setText("Кількість:");

        availableEmployees.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        departmentLabel1.setText("Товар:");

        number.setMinimumSize(new java.awt.Dimension(80, 20));
        number.setPreferredSize(new java.awt.Dimension(80, 20));

        priceLabel.setText("Ціна:");

        price.setMinimumSize(new java.awt.Dimension(80, 20));
        price.setPreferredSize(new java.awt.Dimension(80, 20));

        departmentLabel2.setText("Постачальник:");

        availableProviders.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        content.setLayout(new javax.swing.BoxLayout(content, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(content);

        showSelectedProviderGoods.setText("Переглянути товари постачальника");
        showSelectedProviderGoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSelectedProviderGoodsActionPerformed(evt);
            }
        });

        okButton.setText("+");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(nameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(availableEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(departmentLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(availableProviders, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(showSelectedProviderGoods, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(departmentLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(availableGoods, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(departmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(performButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availableEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(departmentLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availableProviders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(showSelectedProviderGoods)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(departmentLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availableGoods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numberLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(departmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(performButton))
        );

        departmentLabel.getAccessibleContext().setAccessibleName("id");

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void performButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performButtonActionPerformed
        ArrayList<Goods> goods = new ArrayList<Goods>();
        Component[] children = content.getComponents();
        for (int i = 0; i < children.length; ++i) {
            if (children[i].isVisible()) {
                GoodsPreviewItem item = (GoodsPreviewItem) children[i];
                if (item != null) {
                    Goods goodsItem = goodsMap.get(item.getLabelName());
                    goodsItem.numberInSmth = item.getLabelNumber();
                    goodsItem.price = item.getLabelPrice();
                    goods.add(goodsItem);
                }
            }
        }
        
        ActionParams params = new ActionParams();
        String providerName = String.valueOf(availableProviders.getSelectedItem());
        params.dataArr = new Object[3];
        params.dataArr[0] = providersMap.get(providerName).id;
        String employeeName = String.valueOf(availableEmployees.getSelectedItem());
        params.dataArr[1] = employeeMap.get(employeeName).id;
        params.dataArr[2] = date.getText();
        params.data = goods;
        try {
            ActionManager.getInstance().performAction(ActionManager.Action.ADD_ORDERING, params);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddOrdering2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_performButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
       String goodsName = String.valueOf(availableGoods.getSelectedItem());
        Goods goodsItem = goodsMap.get(goodsName);
        if (price.getText() != null && !"".equals(price.getText())
            && number.getText() != null && !"".equals(number.getText())) {
            GoodsPreviewItem item = new GoodsPreviewItem();
            item.setLabelName(goodsItem.name);
            item.setLabelNumber(number.getText());
            item.setLabelPrice(price.getText());
            content.add(item);
            content.repaint();
            content.revalidate();
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void showSelectedProviderGoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSelectedProviderGoodsActionPerformed
        addAvailableGoods();
    }//GEN-LAST:event_showSelectedProviderGoodsActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> availableEmployees;
    private javax.swing.JComboBox<String> availableGoods;
    private javax.swing.JComboBox<String> availableProviders;
    private javax.swing.JPanel content;
    private javax.swing.JTextField date;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JLabel departmentLabel1;
    private javax.swing.JLabel departmentLabel2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JTextField number;
    private javax.swing.JLabel numberLabel1;
    private javax.swing.JButton okButton;
    private javax.swing.JButton performButton;
    private javax.swing.JTextField price;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JButton showSelectedProviderGoods;
    // End of variables declaration//GEN-END:variables
}
