/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopfinal.gui;

import shopfinal.ButtonActionHolder;

public class AddProvider extends javax.swing.JPanel {
     public ButtonActionHolder actionHolder = null;
    /**
     * Creates new form FindById
     */
    public AddProvider() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        performButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(435, 600));
        setMinimumSize(new java.awt.Dimension(435, 600));
        setPreferredSize(new java.awt.Dimension(435, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Додати постачальника");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 160, 30));

        nameLabel.setText("Назва:");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 80, 30));
        nameLabel.getAccessibleContext().setAccessibleName("id");

        name.setMinimumSize(new java.awt.Dimension(80, 20));
        name.setPreferredSize(new java.awt.Dimension(80, 20));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 220, 30));

        performButton.setText("Виконати");
        performButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performButtonActionPerformed(evt);
            }
        });
        add(performButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 140, -1));

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void performButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performButtonActionPerformed
        if (actionHolder != null) {
            actionHolder.performAction();
        }
    }//GEN-LAST:event_performButtonActionPerformed

    public String getLabelName() {
        if (name.getText() != null && name.getText() != "") {
            return name.getText();
        }
        
        return "";
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton performButton;
    // End of variables declaration//GEN-END:variables
}
