/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopfinal.gui;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class DepartmentItem extends javax.swing.JPanel {
    /**
     * Creates new form PurchaseItem
     */
    public DepartmentItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        idLabel1 = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(487, 110));
        setMinimumSize(new java.awt.Dimension(487, 110));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(487, 110));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 100, 20));
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 360, 20));

        title.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Відділ");
        title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 180, 30));

        idLabel1.setText("id:");
        add(idLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 30, 20));

        nameLabel1.setText("Назва:");
        add(nameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 60, 20));
    }// </editor-fold>//GEN-END:initComponents
 
    public void setLabelId(String d) {
        id.setText(d);
    }
    
    public void setLabelName(String n) {
        name.setText(n);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel id;
    private javax.swing.JLabel idLabel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
