/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopfinal.gui;

import shopfinal.ButtonActionHolder;

public class EmployeeItem extends javax.swing.JPanel {
     public ButtonActionHolder actionHolder = null;
    /**
     * Creates new form FindById
     */
    public EmployeeItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        department = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        pib = new javax.swing.JLabel();
        departmentLabel = new javax.swing.JLabel();
        pibLabel = new javax.swing.JLabel();
        costLabel = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(488, 225));
        setMinimumSize(new java.awt.Dimension(488, 225));
        setPreferredSize(new java.awt.Dimension(488, 225));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Працівник");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 140, 30));
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 100, 20));
        id.getAccessibleContext().setAccessibleName("id");

        add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 320, 20));

        idLabel.setText("id:");
        add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 30, 20));
        add(pib, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 320, 20));

        departmentLabel.setText("Відділ:");
        add(departmentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 70, 20));

        pibLabel.setText("ПІБ:");
        add(pibLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 50, 20));

        costLabel.setText("Оклад:");
        add(costLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 50, 20));
        add(cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 320, 20));

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    public int getId() {
        if (id.getText() != null && id.getText() != "") {
            return Integer.parseInt(id.getText());
        }
        
        return 1;
    }
    
    public void setLabelPIB(String p) {
        pib.setText(p);
    }
    
    public void setLabelId(String d) {
        id.setText(d);
    }
    
    public void setLabelCost(String c) {
        cost.setText(c);
    }
    
    public void setLabelDepartment(String d) {
        department.setText(d);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cost;
    private javax.swing.JLabel costLabel;
    private javax.swing.JLabel department;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JLabel id;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel pib;
    private javax.swing.JLabel pibLabel;
    // End of variables declaration//GEN-END:variables
}
