/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopfinal.gui;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class GoodsItem extends javax.swing.JPanel {
    /**
     * Creates new form PurchaseItem
     */
    public GoodsItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        numberLabel = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        provider = new javax.swing.JLabel();
        number = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        actualPrice = new javax.swing.JLabel();
        providerLabel = new javax.swing.JLabel();
        actualPriceLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(488, 211));
        setMinimumSize(new java.awt.Dimension(488, 211));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(488, 211));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 270, 20));

        numberLabel.setText("Кількість:");
        add(numberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 80, 20));
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 100, 20));

        idLabel.setText("id:");
        add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 30, 20));
        add(provider, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 270, 20));
        add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 120, 20));

        title.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Товар");
        title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 180, 30));

        nameLabel.setText("Назва:");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 60, 20));
        add(actualPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 110, 20));

        providerLabel.setText("Постачальник:");
        add(providerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, 20));

        actualPriceLabel.setText("Актуальна ціна за од.:");
        add(actualPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 130, 20));
    }// </editor-fold>//GEN-END:initComponents

    public void setLabelNumber(String d) {
        number.setText(d);
    }
    
    public void setLabelId(String d) {
        id.setText(d);
    }
    
    public void setLabelName(String day) {
        name.setText(day);
    }
    
    public void setLabelProvider(String price) {
        provider.setText(price);
    }
    
    public void setLabelActualPrice(String p) {
        actualPrice.setText(p);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualPrice;
    private javax.swing.JLabel actualPriceLabel;
    private javax.swing.JLabel id;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel number;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JLabel provider;
    private javax.swing.JLabel providerLabel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
