/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopfinal.gui;

import java.awt.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import shopfinal.managers.ActionManager;
import shopfinal.managers.ActionManager.ActionParams;
import shopfinal.managers.ActionManager.Result;

/**
 *
 * @author User
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    private JPanel leftPanel;

    public MainWindow() {
        initComponents();
        setUpOnFirstLaunch();
    }

    private void setUpOnFirstLaunch() {
       setResizable(false);
       setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Goods = new javax.swing.JMenu();
        FindGoodsById = new javax.swing.JMenuItem();
        ShowAllGoods = new javax.swing.JMenuItem();
        AddGoods = new javax.swing.JMenuItem();
        RemoveGoods = new javax.swing.JMenuItem();
        Employee = new javax.swing.JMenu();
        Purchase = new javax.swing.JMenu();
        FindPurchaseById = new javax.swing.JMenuItem();
        AddPurchase = new javax.swing.JMenuItem();
        ShowPurchase = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        ShowAllPurchases = new javax.swing.JMenuItem();
        RemovePurchase = new javax.swing.JMenuItem();
        Provider = new javax.swing.JMenu();
        Analysis = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        Reckoning = new javax.swing.JMenu();
        Settings = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        Goods.setText("Товар");

        FindGoodsById.setText("Знайти за id");
        FindGoodsById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindGoodsByIdActionPerformed(evt);
            }
        });
        Goods.add(FindGoodsById);

        ShowAllGoods.setText("Показати усі");
        ShowAllGoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAllGoodsActionPerformed(evt);
            }
        });
        Goods.add(ShowAllGoods);

        AddGoods.setText("Додати");
        Goods.add(AddGoods);

        RemoveGoods.setText("Видалити");
        Goods.add(RemoveGoods);

        jMenuBar1.add(Goods);

        Employee.setText("Працівник");
        jMenuBar1.add(Employee);

        Purchase.setText("Покупка");

        FindPurchaseById.setText("Знайти за id");
        FindPurchaseById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindPurchaseByIdActionPerformed(evt);
            }
        });
        Purchase.add(FindPurchaseById);

        AddPurchase.setText("Додати");
        AddPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPurchaseActionPerformed(evt);
            }
        });
        Purchase.add(AddPurchase);

        ShowPurchase.setText("Показати");

        jMenuItem5.setText("За дату D");
        ShowPurchase.add(jMenuItem5);

        jMenuItem6.setText("З дати D1 по дату D2");
        ShowPurchase.add(jMenuItem6);

        ShowAllPurchases.setText("Усі");
        ShowAllPurchases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAllPurchasesActionPerformed(evt);
            }
        });
        ShowPurchase.add(ShowAllPurchases);

        Purchase.add(ShowPurchase);

        RemovePurchase.setText("Видалити");
        RemovePurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemovePurchaseActionPerformed(evt);
            }
        });
        Purchase.add(RemovePurchase);

        jMenuBar1.add(Purchase);

        Provider.setText("Постачальник");
        jMenuBar1.add(Provider);

        Analysis.setText("Аналіз");

        jMenuItem13.setText("Надходження товарів");
        Analysis.add(jMenuItem13);

        jMenuBar1.add(Analysis);

        Reckoning.setText("Облік");
        jMenuBar1.add(Reckoning);

        Settings.setText("Налаштування");
        Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsMouseClicked(evt);
            }
        });
        jMenuBar1.add(Settings);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemovePurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemovePurchaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemovePurchaseActionPerformed

    private void FindGoodsByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindGoodsByIdActionPerformed
        addFindByIdPanel();
    }//GEN-LAST:event_FindGoodsByIdActionPerformed

    private void ShowAllPurchasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAllPurchasesActionPerformed
        addShowAllPanel();
    }//GEN-LAST:event_ShowAllPurchasesActionPerformed

    private void FindPurchaseByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindPurchaseByIdActionPerformed
        addFindByIdPanel();
    }//GEN-LAST:event_FindPurchaseByIdActionPerformed

    private void ShowAllGoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAllGoodsActionPerformed
        addShowAllPanel();
    }//GEN-LAST:event_ShowAllGoodsActionPerformed

    private void SettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseClicked
        removeLeftPanel();
        leftPanel = new Settings();
        add(leftPanel);
        refresh();
    }//GEN-LAST:event_SettingsMouseClicked

    private void AddPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPurchaseActionPerformed
        removeLeftPanel();
        leftPanel = new AddPurchase();
        add(leftPanel);
        //leftPanel.add(new GoodsItem());
        //add right panel here;
        refresh();
    }//GEN-LAST:event_AddPurchaseActionPerformed

    private void addShowAllPanel() {
        removeLeftPanel();
        leftPanel = new ShowAll();
        add(leftPanel);
        //add right panel here;
        refresh();
    }

    private void addFindByIdPanel() {
        removeLeftPanel();
        leftPanel = new FindById();
        add(leftPanel);
        //add right panel here
        refresh();
    }

    private void removeLeftPanel() {
        if (leftPanel != null) {
            remove(leftPanel);
        }
    }

    public void refresh() {
        revalidate();
        repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddGoods;
    private javax.swing.JMenuItem AddPurchase;
    private javax.swing.JMenu Analysis;
    private javax.swing.JMenu Employee;
    private javax.swing.JMenuItem FindGoodsById;
    private javax.swing.JMenuItem FindPurchaseById;
    private javax.swing.JMenu Goods;
    private javax.swing.JMenu Provider;
    private javax.swing.JMenu Purchase;
    private javax.swing.JMenu Reckoning;
    private javax.swing.JMenuItem RemoveGoods;
    private javax.swing.JMenuItem RemovePurchase;
    private javax.swing.JMenu Settings;
    private javax.swing.JMenuItem ShowAllGoods;
    private javax.swing.JMenuItem ShowAllPurchases;
    private javax.swing.JMenu ShowPurchase;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
