/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopfinal.gui;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class OrderingItem extends javax.swing.JPanel {
    private DefaultTableModel  model;
    /**
     * Creates new form PurchaseItem
     */
    public OrderingItem() {
        initComponents();
        model = (DefaultTableModel) purchaseGoods.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        providerName = new javax.swing.JLabel();
        providerNameLabel = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        employee = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        purchaseGoods = new javax.swing.JTable();
        dateLabel = new javax.swing.JLabel();
        employeeLabel = new javax.swing.JLabel();
        weekDayLabel = new javax.swing.JLabel();
        weekDay = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(488, 337));
        setMinimumSize(new java.awt.Dimension(488, 337));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(488, 337));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(providerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 350, 20));

        providerNameLabel.setText("Постачальник:");
        add(providerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, 20));
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 100, 20));

        idLabel.setText("id:");
        add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 30, 20));
        add(employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 330, 20));
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 110, 20));

        title.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Замовлення");
        title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 180, 30));

        purchaseGoods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Назва товару", "Кількість"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(purchaseGoods);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 470, 150));

        dateLabel.setText("Дата:");
        add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, 20));

        employeeLabel.setText("ПІБ працівника:");
        add(employeeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 110, 20));

        weekDayLabel.setText("День тижня:");
        add(weekDayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 20));
        add(weekDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 140, 20));
    }// </editor-fold>//GEN-END:initComponents

    public void setLabelDate(String d) {
        date.setText(d);
    }
    
    public void setLabelId(String d) {
        id.setText(d);
    }
    
    public void setDayOfTheWeek(String day) {
        weekDay.setText(day);
    }

    public void createRowInTable(String name, int number) {
        model.addRow(new Object[] { name, number});
    }
    
    public void setEmployeeName(String n) {
        employee.setText(n);
    }
    
    public void setProviderName(String pn) {
        providerName.setText(pn);
    }
    
    //public void 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel employee;
    private javax.swing.JLabel employeeLabel;
    private javax.swing.JLabel id;
    private javax.swing.JLabel idLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel providerName;
    private javax.swing.JLabel providerNameLabel;
    private javax.swing.JTable purchaseGoods;
    private javax.swing.JLabel title;
    private javax.swing.JLabel weekDay;
    private javax.swing.JLabel weekDayLabel;
    // End of variables declaration//GEN-END:variables
}
