/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopfinal.gui;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class OrderingItem extends javax.swing.JPanel {
    private DefaultTableModel  model;
    /**
     * Creates new form PurchaseItem
     */
    public OrderingItem() {
        initComponents();
        model = (DefaultTableModel) orderingGoods.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        status = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        employee = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();
        weekDayLabel = new javax.swing.JLabel();
        weekDay = new javax.swing.JLabel();
        providerNameLabel1 = new javax.swing.JLabel();
        providerName = new javax.swing.JLabel();
        performOrdering = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderingGoods = new javax.swing.JTable();
        employeeLabel1 = new javax.swing.JLabel();
        totalCostLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(488, 460));
        setMinimumSize(new java.awt.Dimension(488, 460));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(488, 460));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 180, 20));

        statusLabel.setText("Статус:");
        add(statusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 60, 20));
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 100, 20));

        idLabel.setText("id:");
        add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 30, 20));
        add(employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 330, 20));
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 110, 20));

        title.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Замовлення");
        title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 180, 30));

        dateLabel.setText("Дата:");
        add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, 20));
        add(cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 120, 20));

        weekDayLabel.setText("День тижня:");
        add(weekDayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 20));
        add(weekDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 140, 20));

        providerNameLabel1.setText("Постачальник:");
        add(providerNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, 20));
        add(providerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 350, 20));

        performOrdering.setText("Виконати замовлення");
        performOrdering.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performOrderingActionPerformed(evt);
            }
        });
        add(performOrdering, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 210, 30));

        orderingGoods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Назва товару", "Вартість за од", "Кількість", "Загальна вартість (грн)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderingGoods);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 470, 150));

        employeeLabel1.setText("ПІБ працівника:");
        add(employeeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 110, 20));

        totalCostLabel1.setText("Загальна вартість:");
        add(totalCostLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 120, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void performOrderingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performOrderingActionPerformed
        setStatus(true);
    }//GEN-LAST:event_performOrderingActionPerformed

    public void setLabelDate(String d) {
        date.setText(d);
    }
    
    public void setLabelId(String d) {
        id.setText(d);
    }
    
    public void setDayOfTheWeek(String day) {
        weekDay.setText(day);
    }

    public void createRowInTable(String name, double price, int number, double totalPrice) {
        model.addRow(new Object[] { name, price, number, totalPrice});
    }
    
    public void setEmployeeName(String n) {
        employee.setText(n);
    }
    
    public void setProviderName(String pn) {
        providerName.setText(pn);
    }
    
    public void setTotalCost(String c) {
        cost.setText(c);
    }
    
    public void setStatus(boolean isPerformed) {
        if (isPerformed) {
            status.setText("Виконано");
            performOrdering.setVisible(false);
        } else {
            status.setText("Не виконано");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cost;
    private javax.swing.JLabel date;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel employee;
    private javax.swing.JLabel employeeLabel1;
    private javax.swing.JLabel id;
    private javax.swing.JLabel idLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderingGoods;
    private javax.swing.JButton performOrdering;
    private javax.swing.JLabel providerName;
    private javax.swing.JLabel providerNameLabel1;
    private javax.swing.JLabel status;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel title;
    private javax.swing.JLabel totalCostLabel1;
    private javax.swing.JLabel weekDay;
    private javax.swing.JLabel weekDayLabel;
    // End of variables declaration//GEN-END:variables
}
