/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopfinal.gui;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class PurchaseItem extends javax.swing.JPanel {
    private DefaultTableModel  model;
    /**
     * Creates new form PurchaseItem
     */
    public PurchaseItem() {
        initComponents();
        model = (DefaultTableModel) purchaseGoods.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        weekDayLabel = new javax.swing.JLabel();
        weekDay = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        dateLabel1 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        purchaseGoods = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(488, 300));
        setMinimumSize(new java.awt.Dimension(488, 300));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(488, 300));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(weekDayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 140, 20));

        weekDay.setText("День тижня:");
        add(weekDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 20));
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 100, 20));

        idLabel.setText("id:");
        add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 30, 20));

        dateLabel1.setText("Дата:");
        add(dateLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, 20));
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 110, 20));

        title.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Покупка");
        title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 180, 30));

        purchaseGoods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Назва товару", "Ціна за одиницю", "Кількість (од)", "Загальна ціна (грн)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(purchaseGoods);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 470, 180));
    }// </editor-fold>//GEN-END:initComponents

    public void setLabelDate(String d) {
        date.setText(d);
    }
    
    public void setLabelId(String d) {
        id.setText(d);
    }
    
    public void setLabelWeekDay(String wd) {
        weekDay.setText(wd);
    }
    
    public void setDayOfTheWeek(String day) {
        weekDay.setText(day);
    }

    public void createRowInTable(String name, double price, int number, double totalPrice) {
       model.addRow(new Object[] { name, price, number, totalPrice});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JLabel dateLabel1;
    private javax.swing.JLabel id;
    private javax.swing.JLabel idLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable purchaseGoods;
    private javax.swing.JLabel title;
    private javax.swing.JLabel weekDay;
    private javax.swing.JLabel weekDayLabel;
    // End of variables declaration//GEN-END:variables
}
