/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopfinal.gui;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import shopfinal.models.Goods;

/**
 *
 * @author User
 */
public class PurveyanceItem extends javax.swing.JPanel {
    private DefaultTableModel  model;
    /**
     * Creates new form PurchaseItem
     */
    public PurveyanceItem() {
        initComponents();
        model = (DefaultTableModel) purveyanceGoods.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        purveyanceGoods = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(488, 337));
        setMinimumSize(new java.awt.Dimension(488, 337));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(488, 337));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 100, 20));

        idLabel.setText("id:");
        add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 30, 20));

        title.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Поставка");
        title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 180, 30));

        purveyanceGoods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Назва товару", "Кількість"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(purveyanceGoods);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 470, 240));
    }// </editor-fold>//GEN-END:initComponents

    public void setLabelId(String d) {
        id.setText(d);
    }

    public void createRowInTable(Goods goods) {
       model.addRow(new Object[] { goods.name, goods.numberInSmth});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel id;
    private javax.swing.JLabel idLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable purveyanceGoods;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
